### ISSUE TITLE
Error: EACCES: permission denied, open '2020-8-2.log' 

### ISSUE THREAD

**Issue by crustyclown71** [samuelcardillo/MMORPGMaker-MV#11]
Hi, 
i have a problem connect to my Server.
I modified the IP from 127.0.0.1 to my dedicated Server's IP
By Login it seems to connect but then exit with Error:

/home/myuser/MMORPGMaker-MV/server/core/security.js:136 
                                           if (err) throw err;                                                                                   ^                                                                                                                                                                          Error: EACCES: permission denied, open '2020-8-2.log'   
And Server ends.
The rethink ist still alive

Name and Password are correct

Please help me ;)

**Comment by samuelcardillo** [comment]
It looks like it is an error of chmod coming from your own system, nothing we can really do in terms of the project itself.
